// 分厂适配配置：每份简历据此重排/重帧
// direction: "engineer" | "pm"
// techOrder: 工程方向技术栈类目优先级（其他类目随后）
// phaseOrder: 项目 Phase 重排（其余按默认序追加）
// keywords: 嵌入「岗位匹配关键词」并用于 PM 技能标签
// summaryHook: 拼接在个人总结前的定向一句话
// url: 官方招聘入口（短链，用于 docx 页脚与适配包）；urlDetail: 岗位示例直链（可选）

export const companies = [
  // ===== 第一梯队：五大模型厂 =====
  {
    id: "bytedance-seed",
    name: "字节 Seed",
    direction: "engineer",
    objective: "大模型 Agent 框架工程师 / AI 搜索 Agent 算法工程师",
    summaryHook: "面向字节 Seed 的 Agent 框架与搜索 Agent 方向：",
    techOrder: ["Agent能力", "RAG与检索", "编排与框架", "模型与训练", "工程"],
    phaseOrder: ["D", "E", "C", "F", "A", "B", "G", "H"],
    keywords: ["Agent 框架", "Planning/Execution", "Tool-Use", "Memory", "Reflection", "Agent 评测", "SWE-Bench", "RAG", "搜索算法"],
    note: "强调评测闭环 + 多 Agent 编排 + 搜索式 RAG + 推理 Benchmark 化",
    url: "https://jobs.bytedance.com/",
    urlDetail: "https://jobs.bytedance.com/experienced/position/7596960769942849845/detail",
  },
  {
    id: "tencent-hunyuan",
    name: "腾讯混元",
    direction: "engineer",
    objective: "混元大模型 Agent 应用开发工程师",
    summaryHook: "面向腾讯混元的 Agent 构建与业务落地方向：",
    techOrder: ["RAG与检索", "Agent能力", "模型与训练", "编排与框架", "工程"],
    phaseOrder: ["C", "B", "G", "D", "E", "A", "F", "H"],
    keywords: ["混元", "RAG 防幻觉", "多轮对话", "Agent 强化", "Post-training", "记忆", "事实核查"],
    note: "强调 RAG 防幻觉 + 记忆多轮 + 混元优先 + 反思强化",
    url: "https://careers.tencent.com/",
    urlDetail: "https://careers.tencent.com/jobdesc.html?postId=2031289374469160960",
  },
  {
    id: "zhipu",
    name: "智谱 GLM",
    direction: "engineer",
    objective: "GLM Agent / Multi-Agent 应用开发工程师",
    summaryHook: "面向智谱 GLM 的 Multi-Agent 与 Tool Learning 方向：",
    techOrder: ["Agent能力", "编排与框架", "RAG与检索", "模型与训练", "工程"],
    phaseOrder: ["D", "A", "B", "E", "C", "G", "F", "H"],
    keywords: ["智谱GLM", "Multi-Agent", "Tool Learning", "长文本", "RLHF", "评测", "Function Calling"],
    note: "强调 Multi-Agent + Tool Learning + 长文本 + 评测闭环",
    url: "https://zhipu-ai.jobs.feishu.cn/",
  },
  {
    id: "kimi",
    name: "Kimi（月之暗面）",
    direction: "engineer",
    objective: "大模型推理 / Agent 应用开发工程师",
    summaryHook: "面向 Kimi 的推理框架与 Agentic 方向：",
    techOrder: ["工程", "Agent能力", "RAG与检索", "编排与框架", "模型与训练"],
    phaseOrder: ["F", "G", "E", "C", "D", "A", "B", "H"],
    keywords: ["推理优化", "vLLM", "高并发", "continuous batching", "Function Calling", "结构化输出", "开源"],
    note: "强调推理优化 + 结构化输出 + 评测闭环 + 开源复用",
    url: "https://careers.kimi.com/",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    direction: "engineer",
    objective: "大模型全栈 / 应用开发工程师",
    summaryHook: "面向 DeepSeek 的「既懂算法又懂系统」方向：",
    techOrder: ["工程", "模型与训练", "Agent能力", "编排与框架", "RAG与检索"],
    phaseOrder: ["F", "A", "E", "G", "C", "D", "B", "H"],
    keywords: ["系统优化", "分布式", "零依赖", "极致性能", "开源", "成本自负盈亏", "vLLM"],
    note: "强调系统级 + 推理极致优化 + 开源复用 + 成本自负盈亏",
    url: "https://talent.deepseek.com/",
  },
  {
    id: "deepseek-pm",
    name: "DeepSeek（AI 产品）",
    direction: "pm",
    objective: "AI 产品经理（Agent 方向）",
    summaryHook: "面向 DeepSeek 2026 新设 Agent 产品团队：",
    phaseOrder: ["A", "C", "E", "H", "D", "B", "F", "G"],
    keywords: ["AI 产品", "Agent 产品", "技术同频", "指标设计", "0→1", "跨职能"],
    note: "DeepSeek 2026.6 大规模招聘新增 AI 产品经理/Agent 产品团队，需技术理解力 + 跨职能",
    url: "https://talent.deepseek.com/",
  },

  // ===== 第二梯队：典型中小厂 =====
  {
    id: "jd",
    name: "京东",
    direction: "pm",
    objective: "AI Agent 产品经理",
    summaryHook: "面向京东「抹平技术鸿沟、低代码构建 Agent」方向：",
    phaseOrder: ["A", "C", "E", "H", "B", "D", "F", "G"],
    keywords: ["低代码", "Agent 生态", "可解释", "竞品分析", "留存", "自然语言构建"],
    note: "京东 AI Agent 产品经理：让非技术人员用低代码/自然语言构建部署管理 AI Agent",
    url: "https://zhaopin.jd.com/",
  },
  {
    id: "kuaishou",
    name: "快手",
    direction: "engineer",
    objective: "大模型 Agent 研发工程师",
    summaryHook: "面向快手的企业应用级 Agent 方向：",
    techOrder: ["RAG与检索", "Agent能力", "编排与框架", "工程", "模型与训练"],
    phaseOrder: ["C", "A", "D", "E", "G", "B", "F", "H"],
    keywords: ["LangChain", "业务接口", "检索决策", "Prompt 优化", "评估指标", "企业应用"],
    note: "快手大模型 Agent 研发：构建可调用大模型服务 + 业务接口，对话/检索/自动决策",
    url: "https://zhaopin.kuaishou.cn/",
  },
  {
    id: "kuaishou-pm",
    name: "快手（Agent 运营）",
    direction: "pm",
    objective: "大模型运营专家（Agent 搭建）",
    summaryHook: "面向快手大模型运营（Agent 搭建与评估）方向：",
    phaseOrder: ["C", "E", "A", "D", "H", "B", "F", "G"],
    keywords: ["Agent 搭建", "评估指标", "策略", "业务拆解", "可解释", "迭代"],
    note: "快手大模型运营专家：拆解业务场景、模型策略与评估指标",
    url: "https://zhaopin.kuaishou.cn/",
  },
  {
    id: "stepfun",
    name: "阶跃星辰",
    direction: "engineer",
    objective: "多模态 / Agent 应用开发工程师",
    summaryHook: "面向阶跃星辰的多模态与端侧 Agent 方向：",
    techOrder: ["RAG与检索", "模型与训练", "Agent能力", "编排与框架", "工程"],
    phaseOrder: ["C", "F", "D", "G", "A", "B", "E", "H"],
    keywords: ["多模态 RAG", "端侧量化蒸馏", "移动答疑", "Agent", "长文本"],
    note: "阶跃星辰：多模态大模型与智能应用（文本/图像/语音），端侧 AI",
    url: "https://www.stepfun.com/",
  },
  {
    id: "yushu",
    name: "宇树科技",
    direction: "engineer",
    objective: "具身 Agent 应用开发工程师",
    summaryHook: "面向宇树科技的具身智能 Agent 方向：",
    techOrder: ["Agent能力", "工程", "模型与训练", "编排与框架", "RAG与检索"],
    phaseOrder: ["D", "F", "A", "G", "C", "B", "E", "H"],
    keywords: ["机器人任务规划", "端侧部署", "低延迟", "工具调用", "数据飞轮", "具身 Agent"],
    note: "宇树：人形机器人量产龙头，机器人任务规划/自然语言交互/具身 Agent",
    url: "https://www.unitree.com/cn/position",
  },
  {
    id: "zhiyuan",
    name: "智元机器人",
    direction: "engineer",
    objective: "具身 Agent 应用开发工程师",
    summaryHook: "面向智元机器人的具身智能 Agent 方向：",
    techOrder: ["Agent能力", "工程", "模型与训练", "编排与框架", "RAG与检索"],
    phaseOrder: ["D", "F", "A", "G", "C", "B", "E", "H"],
    keywords: ["具身 Agent", "数据飞轮", "工业落地", "任务规划", "端侧部署"],
    note: "智元：具身智能头部，具身 Agent / 数据飞轮 / 工业落地",
    url: "https://www.agibot.com/",
  },
  {
    id: "galaxy",
    name: "银河通用",
    direction: "engineer",
    objective: "具身 Agent 应用开发工程师",
    summaryHook: "面向银河通用的具身智能平台方向：",
    techOrder: ["Agent能力", "工程", "模型与训练", "编排与框架", "RAG与检索"],
    phaseOrder: ["D", "F", "A", "G", "C", "B", "E", "H"],
    keywords: ["具身 Agent", "平台化", "多机器人编排", "端侧部署", "任务规划"],
    note: "银河通用：具身智能平台 / 工业落地头部",
    url: "https://www.galbot.com/",
  },
  {
    id: "alibaba-tongyi",
    name: "阿里通义",
    direction: "engineer",
    objective: "通义大模型 Agent 应用开发工程师",
    summaryHook: "面向阿里通义的企业级 Agent 落地方向：",
    techOrder: ["RAG与检索", "Agent能力", "编排与框架", "模型与训练", "工程"],
    phaseOrder: ["C", "G", "A", "D", "E", "B", "F", "H"],
    keywords: ["通义", "RAG 数据飞轮", "企业落地", "百炼", "多厂商"],
    note: "阿里通义：通义大模型 / RAG 数据飞轮 / 企业落地 / 百炼平台",
    url: "https://talent.alibaba.com/",
  },
  {
    id: "baidu",
    name: "百度",
    direction: "engineer",
    objective: "文心 / 千帆 Agent 应用开发工程师",
    summaryHook: "面向百度文心千帆的企业 Agent 方向：",
    techOrder: ["RAG与检索", "编排与框架", "Agent能力", "工程", "模型与训练"],
    phaseOrder: ["C", "A", "G", "D", "E", "B", "F", "H"],
    keywords: ["文心", "千帆 AppBuilder", "企业 Agent", "低代码", "检索"],
    note: "百度：文心 / 千帆 AppBuilder / 企业 Agent",
    url: "https://talent.baidu.com/",
  },
  {
    id: "minimax",
    name: "MiniMax",
    direction: "engineer",
    objective: "对话 / Agent 应用开发工程师",
    summaryHook: "面向 MiniMax 的对话与效率 Agent 方向：",
    techOrder: ["Agent能力", "RAG与检索", "编排与框架", "工程", "模型与训练"],
    phaseOrder: ["B", "C", "D", "A", "E", "G", "F", "H"],
    keywords: ["对话 Agent", "多轮记忆", "Prompt", "abab", "效率"],
    note: "MiniMax：对话与效率类产品 / abab 模型",
    url: "https://www.minimax.io/",
  },
  {
    id: "baichuan",
    name: "百川智能",
    direction: "engineer",
    objective: "行业大模型 Agent 应用开发工程师",
    summaryHook: "面向百川的行业大模型 Agent 方向：",
    techOrder: ["RAG与检索", "Agent能力", "编排与框架", "模型与训练", "工程"],
    phaseOrder: ["C", "A", "B", "D", "E", "G", "F", "H"],
    keywords: ["医疗/行业大模型", "行业 RAG", "事实核查", "垂域", "可解释"],
    note: "百川：医疗 / 行业大模型 / Agent",
    url: "https://www.baichuan-ai.com/",
  },
  {
    id: "sensetime",
    name: "商汤",
    direction: "engineer",
    objective: "多模态 Agent 应用开发工程师",
    summaryHook: "面向商汤日日新的多模态 Agent 方向：",
    techOrder: ["RAG与检索", "模型与训练", "Agent能力", "编排与框架", "工程"],
    phaseOrder: ["C", "F", "D", "G", "A", "B", "E", "H"],
    keywords: ["日日新", "多模态 RAG", "视觉 Agent", "端侧", "长文本"],
    note: "商汤：日日新多模态 / Agent 平台",
    url: "https://www.sensetime.com/",
  },
  {
    id: "meituan",
    name: "美团",
    direction: "engineer",
    objective: "本地生活 Agent 应用开发工程师",
    summaryHook: "面向美团本地生活业务的 Agent 方向：",
    techOrder: ["工程", "Agent能力", "RAG与检索", "编排与框架", "模型与训练"],
    phaseOrder: ["A", "C", "D", "F", "E", "G", "B", "H"],
    keywords: ["业务接口", "高并发", "落地指标", "调度", "检索决策"],
    note: "美团：本地生活业务 Agent / 调度",
    url: "https://zhaopin.meituan.com/",
  },
  {
    id: "xinghai",
    name: "星海图",
    direction: "engineer",
    objective: "具身 Agent 应用开发工程师",
    summaryHook: "面向星海图的具身模型与数据方向：",
    techOrder: ["Agent能力", "工程", "模型与训练", "编排与框架", "RAG与检索"],
    phaseOrder: ["D", "F", "A", "G", "C", "B", "E", "H"],
    keywords: ["具身模型", "数据", "端侧", "任务规划", "工具调用"],
    note: "星海图：具身模型与数据层创业公司",
    url: "https://galaxea.zhiye.com/",
  },
  {
    id: "xingdong",
    name: "星动纪元",
    direction: "engineer",
    objective: "具身 Agent 应用开发工程师",
    summaryHook: "面向星动纪元的具身智能 Agent 方向：",
    techOrder: ["Agent能力", "工程", "模型与训练", "编排与框架", "RAG与检索"],
    phaseOrder: ["D", "F", "A", "G", "C", "B", "E", "H"],
    keywords: ["具身 Agent", "端侧部署", "任务规划", "模仿学习", "工具调用"],
    note: "星动纪元：具身智能创业公司",
    url: "https://www.robotera.com/",
  },
  {
    id: "lingchu",
    name: "灵初智能",
    direction: "engineer",
    objective: "具身 Agent 应用开发工程师",
    summaryHook: "面向灵初智能的具身 Agent 方向：",
    techOrder: ["Agent能力", "工程", "模型与训练", "编排与框架", "RAG与检索"],
    phaseOrder: ["D", "F", "A", "G", "C", "B", "E", "H"],
    keywords: ["具身 Agent", "端侧部署", "任务规划", "工具调用", "数据飞轮"],
    note: "灵初智能：具身智能创业公司",
    url: "https://www.psibot.ai/careers_zh/",
  },
];
