from app.models import ServiceItem, ServiceCategory

# 13 项服务目录：10 类审计支持 + 3 类日常运维
CATALOG: list[ServiceItem] = [
    ServiceItem(id="ukey", name="Ukey 制作/调整/回收", category=ServiceCategory.AUDIT_SUPPORT,
                group="审计支持服务", desc="权限介质管理", icon="🔑",
                approval_chain=["运维主管", "安全管理员"], automated=True),
    ServiceItem(id="perm", name="人员角色权限变更", category=ServiceCategory.AUDIT_SUPPORT,
                group="审计支持服务", desc="账号与授权", icon="👥",
                approval_chain=["部门负责人", "运维主管", "安全管理员"], automated=False),
    ServiceItem(id="mail", name="远程邮件帐号及容量调整", category=ServiceCategory.AUDIT_SUPPORT,
                group="审计支持服务", desc="协作通信", icon="✉️",
                approval_chain=["运维主管"], automated=True),
    ServiceItem(id="resource", name="计算存储资源发放", category=ServiceCategory.AUDIT_SUPPORT,
                group="审计支持服务", desc="资源供给", icon="💾",
                approval_chain=["运维主管", "资源管理员"], automated=False),
    ServiceItem(id="ups", name="UPS 应急演练支持", category=ServiceCategory.AUDIT_SUPPORT,
                group="审计支持服务", desc="容灾保障", icon="🔌",
                approval_chain=["运维主管", "分管领导"], automated=False),
    ServiceItem(id="lottery", name="年会抽奖软件演示", category=ServiceCategory.AUDIT_SUPPORT,
                group="审计支持服务", desc="活动支撑", icon="🎁",
                approval_chain=["运维主管"], automated=False),
    ServiceItem(id="web", name="专网网站改版技术支持", category=ServiceCategory.AUDIT_SUPPORT,
                group="审计支持服务", desc="门户建设", icon="🌐",
                approval_chain=["运维主管", "宣传负责人"], automated=False),
    ServiceItem(id="terminal", name="终端领用与维修", category=ServiceCategory.AUDIT_SUPPORT,
                group="审计支持服务", desc="资产签收", icon="🖥️",
                approval_chain=["运维主管"], automated=True),
    ServiceItem(id="meeting", name="视频会议预约", category=ServiceCategory.AUDIT_SUPPORT,
                group="审计支持服务", desc="会议保障", icon="📹",
                approval_chain=["运维主管"], automated=True),
    ServiceItem(id="backup", name="数据备份与恢复", category=ServiceCategory.AUDIT_SUPPORT,
                group="审计支持服务", desc="容灾备份", icon="💽",
                approval_chain=["运维主管", "安全管理员"], automated=True),
    ServiceItem(id="devops", name="计算存储设备运维", category=ServiceCategory.OPS,
                group="日常运维服务", desc="基础设施", icon="🛠️",
                approval_chain=["运维主管"], automated=True),
    ServiceItem(id="appops", name="应用系统运维", category=ServiceCategory.OPS,
                group="日常运维服务", desc="业务系统", icon="⚙️",
                approval_chain=["运维主管"], automated=True),
    ServiceItem(id="platops", name="基础软件平台运维", category=ServiceCategory.OPS,
                group="日常运维服务", desc="中间件/平台", icon="🧩",
                approval_chain=["运维主管"], automated=True),
]
