from app.models import ServiceItem, ServiceCategory

# 13 项服务目录：10 类审计支持 + 3 类日常运维
# 字段依据蓝鲸（BlueKing）经验细化：SLA 分优先级、门户自助化、监控指标纳管、
# 工单模板字段、面向用户的真实痛点、AIOps 赋能价值、典型月单量。
# id / name / category / group / approval_chain / automated 与既有编排/分类器保持一致。
CATALOG: list[ServiceItem] = [
    # ===================== 十大审计技术支持 =====================
    ServiceItem(id="ukey", name="Ukey 制作/调整/回收", category=ServiceCategory.AUDIT_SUPPORT,
                group="审计支持服务", desc="权限介质管理", icon="🔑",
                approval_chain=["运维主管", "安全管理员"], automated=True,
                sla_hours={"P0": 4, "P1": 8, "P2": 24, "P3": 72},
                self_service=True,
                request_fields=["使用人姓名", "所属处室", "用途", "权限级别", "归还/回收原因"],
                pain_point="审计外派频繁、人员流动大，Ukey 介质靠线下登记，漏回收与越权风险高。",
                ai_value="门户自助申请→自动校验角色→双人审批一键路由，临期自动提醒回收。",
                monthly_volume=86),
    ServiceItem(id="perm", name="人员角色权限变更", category=ServiceCategory.AUDIT_SUPPORT,
                group="审计支持服务", desc="账号与授权", icon="👥",
                approval_chain=["部门负责人", "运维主管", "安全管理员"], automated=False,
                sla_hours={"P0": 4, "P1": 8, "P2": 24, "P3": 72},
                self_service=False,
                request_fields=["账号", "目标角色", "数据范围", "有效期", "审批事由"],
                pain_point="权限调整触及被审计数据访问，审批链长易超期，越权隐患难追溯。",
                ai_value="意图识别自动拆单→三级审批（部门负责人/运维主管/安全管理员），全程留痕。",
                monthly_volume=54),
    ServiceItem(id="mail", name="远程邮件帐号及容量调整", category=ServiceCategory.AUDIT_SUPPORT,
                group="审计支持服务", desc="协作通信", icon="✉️",
                approval_chain=["运维主管"], automated=True,
                sla_hours={"P0": 4, "P1": 8, "P2": 24, "P3": 72},
                self_service=True,
                request_fields=["姓名", "所属处室", "远程接入方式", "容量需求", "有效期"],
                pain_point="外派审计组远程办公依赖邮件，开通慢影响进点效率。",
                ai_value="自助开通 + 容量自助扩容，自动化脚本交付，分钟级生效。",
                monthly_volume=41),
    ServiceItem(id="resource", name="计算存储资源发放", category=ServiceCategory.AUDIT_SUPPORT,
                group="审计支持服务", desc="资源供给", icon="💾",
                approval_chain=["运维主管", "资源管理员"], automated=False,
                sla_hours={"P0": 8, "P1": 12, "P2": 24, "P3": 72},
                self_service=False,
                request_fields=["资源类型", "规格", "用途", "归属项目", "预计释放时间"],
                pain_point="数据分析/取数临时需要算力，走采购流程周期长，项目等资源。",
                ai_value="资源模板化发放→自动打标计费→到期回收，GPU/存储弹性供给。",
                monthly_volume=23),
    ServiceItem(id="ups", name="UPS 应急演练支持", category=ServiceCategory.AUDIT_SUPPORT,
                group="审计支持服务", desc="容灾保障", icon="🔌",
                approval_chain=["运维主管", "分管领导"], automated=False,
                sla_hours={"P1": 8, "P2": 24, "P3": 72},
                self_service=False,
                request_fields=["演练时间", "机房", "参与方", "脚本版本", "回切方案"],
                pain_point="容灾演练协调多方、脚本验证靠人工，演练≠真实故障处置能力。",
                ai_value="演练剧本化 + 切换/回切自动化编排，过程全程录像留痕。",
                monthly_volume=8),
    ServiceItem(id="lottery", name="年会抽奖软件演示", category=ServiceCategory.AUDIT_SUPPORT,
                group="审计支持服务", desc="活动支撑", icon="🎁",
                approval_chain=["运维主管"], automated=False,
                sla_hours={"P2": 24, "P3": 72},
                self_service=False,
                request_fields=["活动日期", "参与人数", "抽奖规则", "演示环境"],
                pain_point="活动支撑类需求零散，易被忽略但临场故障影响大。",
                ai_value="标准化演示模板 + 环境预检，避免现场翻车。",
                monthly_volume=3),
    ServiceItem(id="web", name="专网网站改版技术支持", category=ServiceCategory.AUDIT_SUPPORT,
                group="审计支持服务", desc="门户建设", icon="🌐",
                approval_chain=["运维主管", "宣传负责人"], automated=False,
                sla_hours={"P1": 8, "P2": 24, "P3": 72},
                self_service=False,
                request_fields=["栏目/页面", "改版内容", "上线时间", "SSL 证书"],
                pain_point="门户更新依赖外包沟通，改版周期长、合规样式难统一。",
                ai_value="组件化改版 + 合规样式校验 + 证书到期自动预警。",
                monthly_volume=11),
    ServiceItem(id="terminal", name="终端领用与维修", category=ServiceCategory.AUDIT_SUPPORT,
                group="审计支持服务", desc="资产签收", icon="🖥️",
                approval_chain=["运维主管"], automated=True,
                sla_hours={"P0": 4, "P1": 8, "P2": 24, "P3": 72},
                self_service=True,
                request_fields=["设备类型", "数量", "用途", "现场/远程", "故障描述"],
                pain_point="现场审计终端故障直接影响进点，领用/维修登记混乱。",
                ai_value="资产自助领用 + 故障一键报修，备机调度自动匹配。",
                monthly_volume=37),
    ServiceItem(id="meeting", name="视频会议预约", category=ServiceCategory.AUDIT_SUPPORT,
                group="审计支持服务", desc="会议保障", icon="📹",
                approval_chain=["运维主管"], automated=True,
                sla_hours={"P1": 8, "P2": 24, "P3": 72},
                self_service=True,
                request_fields=["会议主题", "时间", "参会方", "带宽要求", "录播"],
                pain_point="跨部门/跨地域会审频繁，会议室与专线冲突靠人工协调。",
                ai_value="日历冲突检测 + 专线自动调度 + 会审录制归档。",
                monthly_volume=62),
    ServiceItem(id="backup", name="数据备份与恢复", category=ServiceCategory.AUDIT_SUPPORT,
                group="审计支持服务", desc="容灾备份", icon="💽",
                approval_chain=["运维主管", "安全管理员"], automated=True,
                sla_hours={"P0": 4, "P1": 8, "P2": 24, "P3": 72},
                self_service=True,
                request_fields=["数据类型", "范围", "频率", "恢复时间点", "异地副本"],
                pain_point="审计底稿误删/勒索风险高，恢复靠运气、无 SLA 保障。",
                ai_value="策略化备份 + 异地副本校验 + 时间点恢复演练，RPO/RTO 可承诺。",
                monthly_volume=29),

    # ===================== 三大日常运维 =====================
    ServiceItem(id="devops", name="计算存储设备运维", category=ServiceCategory.OPS,
                group="日常运维服务", desc="基础设施", icon="🛠️",
                approval_chain=["运维主管"], automated=True,
                sla_hours={"P0": 1, "P1": 2, "P2": 4, "P3": 8},
                self_service=False,
                monitor_metrics=["CPU 使用率", "内存水位", "磁盘空间", "网络丢包", "主机存活", "宕机"],
                request_fields=["设备/集群", "现象", "影响范围", "紧急程度"],
                pain_point="服务器规模大，故障靠人工巡检发现晚，排查耗时长。",
                ai_value="指标秒级采集 + 异常检测 + 故障自愈（自动重启/隔离/扩容）。",
                monthly_volume=0),
    ServiceItem(id="appops", name="应用系统运维", category=ServiceCategory.OPS,
                group="日常运维服务", desc="业务系统", icon="⚙️",
                approval_chain=["运维主管"], automated=True,
                sla_hours={"P0": 1, "P1": 2, "P2": 4, "P3": 8},
                self_service=False,
                monitor_metrics=["接口超时(P95)", "慢 SQL", "登录失败率", "线程池占用", "错误率", "JVM GC"],
                request_fields=["系统", "接口/模块", "现象", "报错信息"],
                pain_point="审计管理系统/底稿系统可用性直接关系进点，故障定位难。",
                ai_value="全链路监控 + 告警收敛 + 根因定位(知识图谱) + 预案自愈。",
                monthly_volume=0),
    ServiceItem(id="platops", name="基础软件平台运维", category=ServiceCategory.OPS,
                group="日常运维服务", desc="中间件/平台", icon="🧩",
                approval_chain=["运维主管"], automated=True,
                sla_hours={"P0": 1, "P1": 2, "P2": 4, "P3": 8},
                self_service=False,
                monitor_metrics=["证书有效期", "中间件队列堆积", "连接池占用", "日志采集延迟", "Nginx 5xx"],
                request_fields=["平台/组件", "现象", "版本", "影响"],
                pain_point="中间件/证书等隐性故障突发，证书过期等低级事故反复发生。",
                ai_value="证书到期预测 + 队列/连接池自动扩缩 + 采集自愈。",
                monthly_volume=0),
]
